Repository COS214-Project-2024/TheCityKings, pull requests merged in 2024-11, with the labels that each got.

#54 CMakeList.txt updated implementation
  CMakeLists.txt
  src/CMakeLists.txt
  src/buildingComposite/CMakeLists.txt
  src/buildingComposite/commercial/CMakeLists.txt
  src/buildingComposite/industrial/CMakeLists.txt
  src/buildingComposite/landmark/CMakeLists.txt
  src/buildingComposite/residential/CMakeLists.txt
  src/buildingFactory/CMakeLists.txt
  src/government/CMakeLists.txt
  src/managers/CMakeLists.txt
  src/satisfaction/CMakeLists.txt
  src/transport/CMakeLists.txt
  src/utility/CMakeLists.txt
  src/visitor/CMakeLists.txt
  test/CMakeLists.txt
  test/buildingComposite/BuildingCompositeTest.cpp
  test/buildingComposite/CMakeLists.txt
  test/visitor/CMakeLists.txt
  test/visitor/TaxRateVisitorTest.cpp
Labels: enhancement

#53 Ruben/VisitorImp
  src/managers/City.cpp
  src/managers/City.h
  src/visitor/BuildingVisitor.h
  src/visitor/LivingCapacityVisitor.cpp
  src/visitor/LivingCapacityVisitor.h
  src/visitor/TaxRateVisitor.cpp
  src/visitor/TaxRateVisitor.h
Labels: enhancement

#68 Tom/interface
  src/main.cpp
  src/managers/Interface.cpp
  src/managers/Interface.h
Labels: enhancement

#69 Integration/b manager
  src/managers/BuildingManager.cpp
  src/managers/BuildingManager.h
  src/managers/City.cpp
  src/managers/City.h
  src/managers/Interface.cpp
  src/transport/TransportManager.h
  src/utility/UtilityFacade.cpp
Labels: bug, enhancement

#71 CMakeList.txt updated to include appropriate libraries where needed b…
  src/CMakeLists.txt
  src/buildingComposite/CMakeLists.txt
  src/buildingComposite/CompositeNeighbourhood.cpp
  src/buildingComposite/CompositeNeighbourhood.h
  src/buildingComposite/commercial/CMakeLists.txt
  src/buildingComposite/industrial/CMakeLists.txt
  src/buildingComposite/landmark/CMakeLists.txt
  src/buildingComposite/residential/CMakeLists.txt
  src/buildingFactory/CMakeLists.txt
  src/government/CMakeLists.txt
  src/managers/BuildingManager.h
  src/managers/CMakeLists.txt
  src/managers/City.h
  src/managers/Interface.h
  src/satisfaction/CMakeLists.txt
  src/transport/CMakeLists.txt
  src/transport/ModeOfTransport.h
  src/utility/CMakeLists.txt
  src/visitor/CMakeLists.txt
Labels: bug

#75 Feature/cond start
  src/buildingComposite/CompositeNeighbourhood.cpp
  src/managers/BuildingManager.cpp
  src/managers/BuildingManager.h
  src/managers/City.cpp
  src/managers/City.h
  src/managers/Interface.cpp
  src/managers/Interface.h
Labels: enhancement, help wanted

#81 Updated UI
  src/buildingComposite/CompositeNeighbourhood.h
  src/managers/Interface.cpp
  src/managers/Interface.h
Labels: enhancement

#85 Interface Commenting
  src/managers/Interface.h
Labels: documentation

#89 Interface and transport integration
  src/managers/BuildingManager.cpp
  src/managers/BuildingManager.h
  src/managers/City.cpp
  src/managers/City.h
  src/managers/Interface.cpp
  src/managers/Interface.h
  src/transport/Airport.cpp
  src/transport/Airport.h
  src/transport/Bus.cpp
  src/transport/Bus.h
  src/transport/Ferry.cpp
  src/transport/Ferry.h
  src/transport/Train.cpp
  src/transport/Train.h
  src/transport/TransportManager.cpp
  src/transport/TransportManager.h
Labels: enhancement
